services:
  - type: web
    name: voila-simulation-periph
    env: python
    plan: free
    buildCommand: "./setup.sh"
    startCommand: "python -m voila Modele_Simulation/Modele_Simulation_Peripherique_Parisien.ipynb --no-browser --port=$PORT --Voila.trust_xheaders=True --Voila.base_url=/"
    envVars: []